index:
    path: /
    controller: App\Controllers\articleController
    action: home

# showOne:
#     path: /article/{id}/{truc}/{machin}
#     controller: App\Controllers\articleController
#     action: showOne
#     methods:
#         - GET
#         - POST

# login:
#     path: /login
#     controller: App\Controllers\SecurityController
#     action: login
